[package]
name = "mapeditor"
version = "0.1.0"
authors = ["Kornelijus Survila <kornholijo@gmail.com>"]

[[bin]]
name = "mapeditor"
path = "src/main.rs"

[dependencies]
byteorder = "*"
cgmath = "*"
clock_ticks = "*"
encoding = "*"
enum_primitive = "*"
glium = "*"
image = "*"
num = "*"